linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - deadcode
    - funlen
    - gocognit
    - wsl

linters-settings:
  # too see which are enabled: GL_DEBUG=gocritic golangci-lint run
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
